### ISSUE TITLE
ListViewer example will not run

### ISSUE THREAD

**Issue by tracymiranda** [jonahkichwacoders/EASE-Python-Examples#1]
Do a run as EASE script for listviewer. User get this in console:

org.eclipse.ease.ScriptExecutionException: Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'uimain' is not defined

**Comment by tracymiranda** [comment]
This is a known issue which can be worked around by closing the Python script shell. 
Release note added to readme.md
Will be fixed with Py4J 0.10.2 (around 20th June)

**Comment by jonahgraham** [comment]
This was fixed by 31d7a3bb1e9e885d311ed1ebcb4392658beb3a44
